services:
  db:
    image: postgres:16-alpine
    container_name: spabooking-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPA_BOOKING_DB_USERNAME}
      POSTGRES_PASSWORD: ${SPA_BOOKING_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spa_booking"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: spabooking-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: spabooking-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPA_BOOKING_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPA_BOOKING_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPA_BOOKING_DB_PASSWORD}

      # Redis config
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redisdata: